import { describe, expect, it } from "vitest";
import { WORKER_PROTOCOL_VERSION, isPhysicsWorkerRequest, isPhysicsWorkerResponse } from "./worker-contract";
const result = { id:"p", type:"phase1-contact-result", ok:true, fixtureId:"f", scenario:"touching", classification:"touching", clearanceMeters:0, penetrationDepthMeters:0, contactCount:1, point:{x:0,y:0,z:0}, normal:{x:0,y:1,z:0} };
describe("physics worker contract", () => {
  it("accepts finite-transform geometry requests", () => { expect(isPhysicsWorkerRequest({ id:"3", type:"run-phase1-contact-query", fixtureId:"f", scenario:"touching", upperTranslationYMeters:-0.16, meshes:[{name:"a",positions:new ArrayBuffer(4),indices:new ArrayBuffer(4),indexComponentType:"uint16"},{name:"b",positions:new ArrayBuffer(4),indices:new ArrayBuffer(4),indexComponentType:"uint32"}] })).toBe(true); });
  it.each([NaN, Infinity, -Infinity])("rejects non-finite request transforms: %s", (number) => { expect(isPhysicsWorkerRequest({ id:"x", type:"run-phase1-contact-query", fixtureId:"f", scenario:"touching", upperTranslationYMeters:number, meshes:[] })).toBe(false); });
  it("accepts every response variant", () => { expect(isPhysicsWorkerResponse({ id:"h", type:"health", ok:true, protocolVersion:WORKER_PROTOCOL_VERSION, rapierVersion:"r", fixtureName:"f" })).toBe(true); expect(isPhysicsWorkerResponse({ id:"s", type:"synthetic-collision-result", ok:true, fixtureName:"f", collided:true, steps:1, finalDynamicY:1 })).toBe(true); expect(isPhysicsWorkerResponse(result)).toBe(true); expect(isPhysicsWorkerResponse({ id:"e", type:"error", ok:false, message:"bad" })).toBe(true); });
  it.each([NaN, Infinity, -Infinity])("rejects non-finite scientific results: %s", (number) => { expect(isPhysicsWorkerResponse({ ...result, clearanceMeters:number })).toBe(false); expect(isPhysicsWorkerResponse({ ...result, penetrationDepthMeters:number })).toBe(false); expect(isPhysicsWorkerResponse({ ...result, point:{x:number,y:0,z:0} })).toBe(false); });
  it("rejects negative or classification-inconsistent measurements", () => { expect(isPhysicsWorkerResponse({ ...result, clearanceMeters:-0.1 })).toBe(false); expect(isPhysicsWorkerResponse({ ...result, classification:"separated", clearanceMeters:0 })).toBe(false); expect(isPhysicsWorkerResponse({ ...result, classification:"penetrating", penetrationDepthMeters:0 })).toBe(false); });
});
