"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import { DRACOLoader } from "three/examples/jsm/loaders/DRACOLoader.js";
import { NEUTRAL_POSE, POSE_LIMITS, metersToMillimeters, type CollisionMeshPayload,type MandibularPose,type PoseResult } from "@/physics/worker-contract";
import { acceptWorkerResponse,type ResponseGate } from "@/physics/ui-response-gate";
import { advanceLesson,type LessonStage } from "@/physics/lesson";
const FIXTURE_ID="phase1-opposing-occlusal-surfaces";
const SEPARATED=NEUTRAL_POSE; const FIRST_CONTACT:MandibularPose={openingMeters:0,protrusionMeters:0,lateralMeters:0};
function cloneBuffer(view:ArrayBufferView){const copy=new Uint8Array(view.byteLength);copy.set(new Uint8Array(view.buffer,view.byteOffset,view.byteLength));return copy.buffer;}
function payload(mesh:THREE.Mesh):CollisionMeshPayload{const p=mesh.geometry.getAttribute("position"),i=mesh.geometry.index;if(!p||!i)throw new Error(`Missing collision buffers for ${mesh.name}`);return{name:mesh.name,positions:cloneBuffer(p.array),indices:cloneBuffer(i.array),indexComponentType:i.array instanceof Uint32Array?"uint32":"uint16"};}
export function ThreeScene(){const hostRef=useRef<HTMLDivElement>(null),workerRef=useRef<Worker|null>(null),mandibleRef=useRef<THREE.Mesh|null>(null),markersRef=useRef<THREE.Points|null>(null),gateRef=useRef<ResponseGate>({pendingIds:new Set(),latestPoseSequence:0}),poseRef=useRef<MandibularPose>(NEUTRAL_POSE),frameRef=useRef<number|undefined>(undefined);const[asset,setAsset]=useState("loading"),[workerState,setWorkerState]=useState("loading"),[error,setError]=useState<string|null>(null),[pose,setPoseState]=useState<MandibularPose>(NEUTRAL_POSE),[result,setResult]=useState<PoseResult|null>(null),[lesson,setLesson]=useState<LessonStage>("start");
 const sendPose=useCallback((next:MandibularPose)=>{poseRef.current=next;setPoseState(next);if(frameRef.current!==undefined)cancelAnimationFrame(frameRef.current);frameRef.current=requestAnimationFrame(()=>{const worker=workerRef.current;if(!worker)return;const sequence=++gateRef.current.latestPoseSequence,id=`pose-${sequence}`;gateRef.current.pendingIds.add(id);worker.postMessage({id,type:"evaluate-mandibular-pose",fixtureId:FIXTURE_ID,sequence,pose:poseRef.current});});},[]);
 useEffect(()=>{const host=hostRef.current;if(!host)return;const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});if(!renderer.capabilities.isWebGL2){queueMicrotask(()=>setError("WebGL2 is required for this educational visualization."));return;}renderer.setPixelRatio(Math.min(devicePixelRatio,2));host.appendChild(renderer.domElement);const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(45,1,.1,100);camera.position.set(3,2.2,4.8);camera.lookAt(0,0,0);scene.add(new THREE.HemisphereLight(0xffffff,0x203040,2.2),new THREE.GridHelper(5,10,0x36506f,0x20354f));const light=new THREE.DirectionalLight(0x7dd3fc,2.5);light.position.set(4,6,3);scene.add(light);const markerGeometry=new THREE.BufferGeometry(),markerMaterial=new THREE.PointsMaterial({size:.075,vertexColors:true,sizeAttenuation:true});const markers=new THREE.Points(markerGeometry,markerMaterial);markersRef.current=markers;scene.add(markers);const draco=new DRACOLoader();draco.setDecoderPath("/draco/");draco.setDecoderConfig({type:"js"});const loader=new GLTFLoader();loader.setDRACOLoader(draco);const worker=new Worker(new URL("../workers/rapier.worker.ts",import.meta.url),{type:"module"});workerRef.current=worker;
 worker.onmessage=(event:MessageEvent<unknown>)=>{const decision=acceptWorkerResponse(event.data,gateRef.current);if(decision.error){setError(decision.error);setWorkerState("error");return;}const response=decision.response;if(!response)return;if(response.type==="error"){setError(response.message);setWorkerState("error");return;}if(response.type==="fixture-ready"){setWorkerState("ready");sendPose(NEUTRAL_POSE);}if(response.type==="mandibular-pose-result"){setResult(response);setLesson(s=>advanceLesson(s,response,poseRef.current));const m=mandibleRef.current,t=response.appliedTransform;m?.position.set(t.translationMeters.x,t.translationMeters.y,t.translationMeters.z);m?.quaternion.set(t.rotationQuaternion.x,t.rotationQuaternion.y,t.rotationQuaternion.z,t.rotationQuaternion.w);const positions=new Float32Array(response.contactSamples.flatMap(c=>[c.pointWorldMeters.x,c.pointWorldMeters.y,c.pointWorldMeters.z]));const colors=new Float32Array(response.contactSamples.flatMap(c=>c.penetrationDepthMeters>0?[1,.25,.2]:[.2,1,.7]));markerGeometry.setAttribute("position",new THREE.BufferAttribute(positions,3));markerGeometry.setAttribute("color",new THREE.BufferAttribute(colors,3));markerGeometry.setDrawRange(0,response.contactSamples.length);}}
 loader.load("/generated/opposing-occlusal-surfaces.glb",gltf=>{const found:THREE.Mesh[]=[];gltf.scene.traverse(o=>{if(o instanceof THREE.Mesh&&(o.name==="OL_COLLISION_UPPER"||o.name==="OL_COLLISION_LOWER")){o.material=new THREE.MeshStandardMaterial({color:o.name.includes("UPPER")?0x9bd5ff:0xffd6a5,roughness:.48,transparent:true,opacity:.9});found.push(o);}});if(found.length!==2){setError("The synthetic fixture could not be validated.");setAsset("error");return;}scene.add(gltf.scene);const upper=found.find(m=>m.name.includes("UPPER"))!,lower=found.find(m=>m.name.includes("LOWER"))!;mandibleRef.current=lower;setAsset("ready");const meshes:[CollisionMeshPayload,CollisionMeshPayload]=[payload(upper),payload(lower)],id="initialize-1";gateRef.current.pendingIds.add(id);worker.postMessage({id,type:"initialize-occlusion-fixture",fixtureId:FIXTURE_ID,meshes},meshes.flatMap(m=>[m.positions,m.indices]));},undefined,()=>{setAsset("error");setError("The synthetic fixture could not be loaded.");});const resize=()=>{renderer.setSize(host.clientWidth,host.clientHeight,false);camera.aspect=host.clientWidth/Math.max(host.clientHeight,1);camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(host);resize();let raf=0;const animate=()=>{renderer.render(scene,camera);raf=requestAnimationFrame(animate);};animate();return()=>{worker.terminate();cancelAnimationFrame(raf);if(frameRef.current!==undefined)cancelAnimationFrame(frameRef.current);observer.disconnect();draco.dispose();markerGeometry.dispose();markerMaterial.dispose();renderer.dispose();host.replaceChildren();};},[sendPose]);
 const field=(key:keyof MandibularPose,label:string,min:number,max:number)=><label>{label}<span>{metersToMillimeters(pose[key]).toFixed(0)} mm</span><input aria-label={label} type="range" min={min} max={max} step={.005} value={pose[key]} disabled={workerState!=="ready"} onChange={e=>sendPose({...pose,[key]:Number(e.target.value)})}/></label>;
 const reset=()=>{setLesson("start");sendPose(NEUTRAL_POSE);};return <div className="phase2"><div ref={hostRef} className="sceneHost" aria-label="Synthetic Three.js contact scene"/><section className="controls" aria-label="Mandibular movement controls"><p>Status: asset {asset}; worker {workerState}. <b>{result?.classification??"awaiting validated result"}</b> · contacts {result?.contactCount??0}</p>{error&&<p role="alert" className="error">{error}</p>}{field("openingMeters","Opening / closing",0,POSE_LIMITS.openingMeters.max)}{field("protrusionMeters","Protrusion (+Z anterior)",0,POSE_LIMITS.protrusionMeters.max)}{field("lateralMeters","Lateral (− left / + right)",POSE_LIMITS.lateralMeters.min,POSE_LIMITS.lateralMeters.max)}<div className="buttons"><button onClick={reset}>Reset neutral</button><button onClick={()=>sendPose(SEPARATED)}>Separated preset</button><button onClick={()=>sendPose(FIRST_CONTACT)}>First-contact preset</button></div><p className="legend"><i className="touch"/> touching <i className="penetrate"/> geometric penetration · {result?.measurementStatus==="unavailable-separated"?"clearance unavailable for interactive separated poses":`penetration ${metersToMillimeters(result?.penetrationDepthMeters??0).toFixed(3)} mm`}</p></section><section className="lesson"><h2>Lesson: move from separation to first contact</h2><p>1. Begin separated. 2. Close to a validated touching result and inspect the markers. 3. Apply at least 5 mm lateral or protrusive movement while contacts remain.</p><p><strong>Progress: {lesson}</strong></p><button onClick={()=>{setLesson("start");sendPose(SEPARATED);}}>Reset / retry lesson</button><p>Results describe deterministic synthetic geometry only—not anatomy, biomechanics, diagnosis, or treatment planning.</p></section></div>}
